### PR TITLE
Adding emscripten build

### PR DESCRIPTION
**Pull request by vespakoen**
This is an experiment to run opencamlib in the browser.
Emscripten's wrapper code is actually very similar to boost python (pretty much a 1:1 copy) so it is very easy to implement.
I already got waterline working with node.js using this build, it is very slow with loading the stl file, so I loaded the stl in nodejs and added the triangles to the STLSurf, which worked pretty fast!

So in theory this also runs in the browser right now, although I didn't test it yet.

### CODE REVIEW

**Comment by vespakoen** [comment]
Got it running in the browser.

screenshot 2019-01-20 at 20 40 24

The opencamlib.js file is 763 KB and the opencamlib.wasm is 335 KB
This is with the `-O3` compiler flag, but without clojure compiler optimisations yet, so it can be even smaller.

**Comment by aewallin** [comment]
hm, OK... this would be really fun/useful if there was a 3D environment that runs in the browser, similar to VTK? (https://kitware.github.io/vtk-js/examples/)
the screen needs to be split between the script that generates the toolpath and the 3D view result.
(or alternatively the same could maybe be done within freecad - but I haven't looked at that in years..)

**Comment by vespakoen** [comment]
There is vtk-js indeed, but isn't viewing / using the data up to the user anyways?
There are many libraries that can visualise 3D in the browser, opencamlib is just needed to generate a list of point lists (`std::vector<std::vector<Point>>`) for the different operations.
In the example code I use a 'browserified' version of the `stl` package to parse stl files in the browser and add it's triangles onto the STLSurf.

**Comment by aewallin** [comment]
I was using VTK for visualizing the algorithms while developing them. There's no dependency in opencamlib on vtk.
What was always missing was an easy to use GUI for these algorithms. I don't know the latest status of heekscad/heekscnc, nor freecad - maybe there is work there?
I'd be much more motivated to work on opencamlib enhancements (e.g. pencil and constant-scallop 3D paths) and openvoronoi (adaptive pocketing) if there was a GUI and people would actually use these libraries...

**Comment by vespakoen** [comment]
I see, there is BlenderCAM as well (which unfortunately uses its own bundled python by default so installation of opencamlib gets even more difficult for it).

I think the biggest problem to this day was the installation of opencamlib.
This is hopefully better now with the updated CMakeLists and the license change.
Having pre-compiled libraries is probably another important step to have more people be able to use opencamlib in the first place (e.g. non-programmers).

This emscipten build could actually be the start of it, for the end user it requires no compilation or installation and is cross platform, someone just need to integrate it in a web-based g-code generator.

I think many projects could benefit from this and hope it's just a matter of time that this library gets used more ;)

**Comment by vespakoen** [comment]
And a version that shows a 3d view of the path https://jsfiddle.net/49hvrjab/3/

**Pull request merged**
